# **Section A: Data Structures & Control Structures**
1.	Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.


In [ ]:
list_int = [1, 2, 3, 4, 5]

# Append
list_int.append(6)
print("After append:", list_int)
# extend
list_int2 = [7, 8, 9]
list_int.extend(list_int2)
print("After extend:", list_int)
# insert
list_int.insert(0, 0)
print("After insert:", list_int)
#remove
list_int.remove(0)
print("After remove:", list_int)
#pop
popped_element = list_int.pop()
print("Popped element:", popped_element)
print("After pop:", list_int)
#index
index_of_5 = list_int.index(5)
print("Index of 5:", index_of_5)
#count
count_of_3 = list_int.count(3)
print("Count of 3:", count_of_3)
#sort
list_int.sort()
print("After sort:", list_int)
#reverse
list_int.reverse()
print("After reverse:", list_int)
#clear
list_int.clear()
print("After clear:", list_int)

After append: [1, 2, 3, 4, 5, 6]
After extend: [1, 2, 3, 4, 5, 6, 7, 8, 9]
After insert: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
After remove: [1, 2, 3, 4, 5, 6, 7, 8, 9]
Popped element: 9
After pop: [1, 2, 3, 4, 5, 6, 7, 8]
Index of 5: 4
Count of 3: 1
After sort: [1, 2, 3, 4, 5, 6, 7, 8]
After reverse: [8, 7, 6, 5, 4, 3, 2, 1]
After clear: []


2. Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [ ]:
students = ("PremKiran", "ViratKohli", "NTR")
students[1] = "MSDhoni"
#tuple is immutable, we cannot chage or modify etc. why: to ensure data safety, reduce memory usage, improve performance
#to change items in tuple we can convert to list and do list operations revert back to tuple


TypeError: 'tuple' object does not support item assignment

In [ ]:
#by converting to list we can do
students_tuple = ("PremKiran", "ViratKohli", "NTR")
students_list = list(students_tuple)
students_list[1] = "MSDhoni"
students_tuple = tuple(students_list)
print(students_tuple)

('PremKiran', 'MSDhoni', 'NTR')


3. Create a set of integers with some duplicate values. Print the set and explain the output.



In [ ]:
set_int = {1,1,2,3,4,4,4,5,6,3,2,8,9}
print(set_int)
#output : set is unordered immutable and contains unique elements all duplicate items removed

{1, 2, 3, 4, 5, 6, 8, 9}


4. Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.




In [ ]:
details ={
    "name":"premkiran",
    "age":24,
    "city":"hyderabad"
}
print("initial dictionary:",details)

details.update({"age":25, "email":"premkiran727@gmail.com"})
print("final dictionary after changes:",details)


initial dictionary: {'name': 'premkiran', 'age': 24, 'city': 'hyderabad'}
final dictionary after changes: {'name': 'premkiran', 'age': 25, 'city': 'hyderabad', 'email': 'premkiran727@gmail.com'}


5. Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [1]:
age = int(input("Enter your age: "))

if age < 0:
    print("Invalid age")
elif age >= 18:
    print("You are eligible to vote")
else:
    print("You are not eligible to vote")

Enter your age: 24
You are eligible to vote


6. Given a 'marks' variable, print the grade:
*  90 and above: 'A'
* 75–89: 'B'
* 50–74: 'C'
* Below 50: 'Fail'


In [ ]:
marks = int(input("enter the marks"))
if marks >= 90:
  print("A")
elif marks >= 75 and marks <= 89:
  print("B")
elif marks >= 50 and marks <= 74:
  print("C")
else:
  print("Fail")

enter the marks52
C


7. Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [ ]:
number = int(input("enter the number"))
if number > 0 and number % 2 ==0:
    print("positive and even")
elif number > 0 and number % 2 != 0:
  print("positive and odd")
elif number == 0:
  print("zero")
else:
  print("negative")

enter the number4
positive and even


# **Section B: Numpy**
8.	Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10


In [1]:
import numpy as np
#Scalar
scalar_arr = np.array(5)
print("Scalar array:",scalar_arr)

#1d array
arr_1d = np.array([1,2,3,4,5])
print("1d array:",arr_1d)

#2d array
arr_2d = np.array([[10,20,30],[40,50,60]])
print("2d array:",arr_2d)

Scalar array: 5
1d array: [1 2 3 4 5]
2d array: [[10 20 30]
 [40 50 60]]


9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().


In [3]:
random_matrix = np.random.randint(0, 101, size=(4, 4))

print(random_matrix)

[[93 58  8  8]
 [70 28 77 17]
 [25 65 37 60]
 [ 3 85 93 33]]


10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.


In [2]:
array_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# **Section C: Exploring Pandas**
11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows

In [4]:
import pandas as pd

# 1. Create a small DataFrame manually with 10 rows
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', 'Grace', 'Henry', 'Alice', 'Ivy'],
    'Age': [25, 30, 22, 28, 35, 27, 32, 29, 25, 31],
    'City': ['New York', 'Paris', 'London', 'Tokyo', 'Berlin', 'Sydney', 'Toronto', 'Boston', 'New York', 'Chicago'],
    'Salary': [70000, 85000, np.nan, 120000, 60000, np.nan, 95000, 80000, 70000, 90000]
}

df = pd.DataFrame(data)
print("--- Original DataFrame ---")
print(df)

# 2. Use .info() and .describe()
print("\n--- DataFrame Info ---")
df.info()

print("\n--- DataFrame Descriptive Statistics ---")
print(df.describe(include='all'))

# 3. Select 'Name' and 'City' columns
name_city_df = df[['Name', 'City']]
print("\n--- Selected 'Name' and 'City' Columns ---")
print(name_city_df)

# 4. Drop 'City' column
df_dropped = df.drop(columns=['City'])
print("\n--- DataFrame after dropping 'City' column ---")
print(df_dropped)

# 5. Fill any missing values in 'Salary' column with the mean
mean_salary = df_dropped['Salary'].mean()
df_dropped['Salary'] = df_dropped['Salary'].fillna(mean_salary)
print(f"\n--- Filled missing Salaries with mean ({mean_salary:.2f}) ---")
print(df_dropped)

# 6. Remove any duplicate rows
df_final = df_dropped.drop_duplicates()
print("\n--- Final DataFrame after removing duplicate rows ---")
print(df_final)


--- Original DataFrame ---
      Name  Age      City    Salary
0    Alice   25  New York   70000.0
1      Bob   30     Paris   85000.0
2  Charlie   22    London       NaN
3    David   28     Tokyo  120000.0
4      Eva   35    Berlin   60000.0
5    Frank   27    Sydney       NaN
6    Grace   32   Toronto   95000.0
7    Henry   29    Boston   80000.0
8    Alice   25  New York   70000.0
9      Ivy   31   Chicago   90000.0

--- DataFrame Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes

--- DataFrame Descriptive Statistics ---
         Name        Age      City         Salary
count      10  10.000000        10       8.000000
unique      9        